apiVersion: apps/v1
kind: Deployment
metadata:
  name: service--notification-deployment
  namespace: shoes-eks
spec:
  selector:
    matchLabels:
      app: service--notification
  template: 
    metadata:
        name: service--notification
        labels:
          app: service--notification
    spec:
        containers:
          - name: service--notification-container
            image: $dck-accountid/$dck-repository:service--notification-$githash
            env:
              - name: SPRING_PROFILES_ACTIVE
                value: "dev,jsonlog"
            ports:
              - containerPort: 5000
              - containerPort: 9190
            livenessProbe:
              httpGet:
                path: /actuator/health
                port: 9190
              initialDelaySeconds: 120
              periodSeconds: 60
              timeoutSeconds: 10
              successThreshold: 1
              failureThreshold: 2
            readinessProbe:
              httpGet:
                path: /actuator/health
                port: 9190
              initialDelaySeconds: 120
              periodSeconds: 10
              timeoutSeconds: 10
            resources:
              limits:
                memory: "600Mi"
                cpu : "400Mi"
              requests:
                memory: "400Mi"
                cpu: "270Mi"